exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
F.
======================================================================
FAIL: testBasic (__main__.CTCLossTest)
Test two batch entries.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pi/.cache/bazel/_bazel_pi/4770c5ca1786316d370c900c0b614a6d/tensorflow/bazel-out/local_linux-opt/bin/tensorflow/python/kernel_tests/ctc_loss_op_test.runfiles/tensorflow/python/kernel_tests/ctc_loss_op_test.py", line 203, in testBasic
    self._testCTCLoss(inputs, seq_lens, labels, loss_truth, grad_truth)
  File "/home/pi/.cache/bazel/_bazel_pi/4770c5ca1786316d370c900c0b614a6d/tensorflow/bazel-out/local_linux-opt/bin/tensorflow/python/kernel_tests/ctc_loss_op_test.runfiles/tensorflow/python/kernel_tests/ctc_loss_op_test.py", line 67, in _testCTCLoss
    self.assertAllClose(tf_loss, loss_truth, atol=1e-6)
  File "/home/pi/.cache/bazel/_bazel_pi/4770c5ca1786316d370c900c0b614a6d/tensorflow/bazel-out/local_linux-opt/bin/tensorflow/python/kernel_tests/ctc_loss_op_test.runfiles/tensorflow/python/framework/test_util.py", line 442, in assertAllClose
    np.testing.assert_allclose(a, b, rtol=rtol, atol=atol)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 1183, in assert_allclose
    verbose=verbose, header=header)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 644, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-06, atol=1e-06

(mismatch 100.0%)
 x: array([ 3.34211779,  5.42262316], dtype=float32)
 y: array([ 3.34210992,  5.42261982], dtype=float32)

----------------------------------------------------------------------
Ran 2 tests in 0.164s

FAILED (failures=1)
not close where =  (array([0]),)
not close lhs =  [ 3.34211779]
not close rhs =  [ 3.34210992]
not close dif =  [  7.86781311e-06]
not close tol =  [  4.34211006e-06]
