exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
F..
======================================================================
FAIL: testBCast_0D (__main__.BinaryOpTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pi/.cache/bazel/_bazel_pi/4770c5ca1786316d370c900c0b614a6d/tensorflow/bazel-out/local_linux-opt/bin/tensorflow/python/kernel_tests/cwise_ops_test.runfiles/tensorflow/python/kernel_tests/cwise_ops_test.py", line 803, in testBCast_0D
    self._testBCastD([1, 3, 2], [1])
  File "/home/pi/.cache/bazel/_bazel_pi/4770c5ca1786316d370c900c0b614a6d/tensorflow/bazel-out/local_linux-opt/bin/tensorflow/python/kernel_tests/cwise_ops_test.runfiles/tensorflow/python/kernel_tests/cwise_ops_test.py", line 791, in _testBCastD
    self._testBCastByFunc(funcs, xs, ys)
  File "/home/pi/.cache/bazel/_bazel_pi/4770c5ca1786316d370c900c0b614a6d/tensorflow/bazel-out/local_linux-opt/bin/tensorflow/python/kernel_tests/cwise_ops_test.runfiles/tensorflow/python/kernel_tests/cwise_ops_test.py", line 759, in _testBCastByFunc
    self._compareBCast(xs, ys, dtype, np_func, tf_func)
  File "/home/pi/.cache/bazel/_bazel_pi/4770c5ca1786316d370c900c0b614a6d/tensorflow/bazel-out/local_linux-opt/bin/tensorflow/python/kernel_tests/cwise_ops_test.runfiles/tensorflow/python/kernel_tests/cwise_ops_test.py", line 727, in _compareBCast
    self._compareCpu(x, y, np_func, tf_func)
  File "/home/pi/.cache/bazel/_bazel_pi/4770c5ca1786316d370c900c0b614a6d/tensorflow/bazel-out/local_linux-opt/bin/tensorflow/python/kernel_tests/cwise_ops_test.runfiles/tensorflow/python/kernel_tests/cwise_ops_test.py", line 448, in _compareCpu
    self.assertAllClose(np_ans, tf_cpu)
  File "/home/pi/.cache/bazel/_bazel_pi/4770c5ca1786316d370c900c0b614a6d/tensorflow/bazel-out/local_linux-opt/bin/tensorflow/python/kernel_tests/cwise_ops_test.runfiles/tensorflow/python/framework/test_util.py", line 442, in assertAllClose
    np.testing.assert_allclose(a, b, rtol=rtol, atol=atol)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 1183, in assert_allclose
    verbose=verbose, header=header)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 644, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-06, atol=1e-06

(mismatch 100.0%)
 x: array([[[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.]]], dtype=float32)
 y: array([[[ 0.99999619,  1.99999237],
        [ 2.99998856,  3.99998474],
        [ 5.        ,  6.        ]]], dtype=float32)

----------------------------------------------------------------------
Ran 3 tests in 44.512s

FAILED (failures=1)
not close where =  (array([0, 0, 0, 0]), array([0, 0, 1, 1]), array([0, 1, 0, 1]))
not close lhs =  [ 1.  2.  3.  4.]
not close rhs =  [ 0.99999619  1.99999237  2.99998856  3.99998474]
not close dif =  [  3.81469727e-06   7.62939453e-06   1.14440918e-05   1.52587891e-05]
not close tol =  [  1.99999613e-06   2.99999238e-06   3.99998862e-06   4.99998441e-06]
