exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
F.
======================================================================
FAIL: testBCast_2D (__main__.BinaryOpTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pi/.cache/bazel/_bazel_pi/4770c5ca1786316d370c900c0b614a6d/tensorflow/bazel-out/local_linux-py3-opt/bin/tensorflow/python/kernel_tests/cwise_ops_test.runfiles/tensorflow/python/kernel_tests/cwise_ops_test.py", line 827, in testBCast_2D
    self._testBCastD([1, 3, 2], [3, 2])
  File "/home/pi/.cache/bazel/_bazel_pi/4770c5ca1786316d370c900c0b614a6d/tensorflow/bazel-out/local_linux-py3-opt/bin/tensorflow/python/kernel_tests/cwise_ops_test.runfiles/tensorflow/python/kernel_tests/cwise_ops_test.py", line 791, in _testBCastD
    self._testBCastByFunc(funcs, xs, ys)
  File "/home/pi/.cache/bazel/_bazel_pi/4770c5ca1786316d370c900c0b614a6d/tensorflow/bazel-out/local_linux-py3-opt/bin/tensorflow/python/kernel_tests/cwise_ops_test.runfiles/tensorflow/python/kernel_tests/cwise_ops_test.py", line 759, in _testBCastByFunc
    self._compareBCast(xs, ys, dtype, np_func, tf_func)
  File "/home/pi/.cache/bazel/_bazel_pi/4770c5ca1786316d370c900c0b614a6d/tensorflow/bazel-out/local_linux-py3-opt/bin/tensorflow/python/kernel_tests/cwise_ops_test.runfiles/tensorflow/python/kernel_tests/cwise_ops_test.py", line 727, in _compareBCast
    self._compareCpu(x, y, np_func, tf_func)
  File "/home/pi/.cache/bazel/_bazel_pi/4770c5ca1786316d370c900c0b614a6d/tensorflow/bazel-out/local_linux-py3-opt/bin/tensorflow/python/kernel_tests/cwise_ops_test.runfiles/tensorflow/python/kernel_tests/cwise_ops_test.py", line 448, in _compareCpu
    self.assertAllClose(np_ans, tf_cpu)
  File "/home/pi/.cache/bazel/_bazel_pi/4770c5ca1786316d370c900c0b614a6d/tensorflow/bazel-out/local_linux-py3-opt/bin/tensorflow/python/kernel_tests/cwise_ops_test.runfiles/tensorflow/python/framework/test_util.py", line 442, in assertAllClose
    np.testing.assert_allclose(a, b, rtol=rtol, atol=atol)
  File "/usr/local/lib/python3.4/dist-packages/numpy/testing/utils.py", line 1391, in assert_allclose
    verbose=verbose, header=header)
  File "/usr/local/lib/python3.4/dist-packages/numpy/testing/utils.py", line 733, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-06, atol=1e-06

(mismatch 50.0%)
 x: array([[[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]]], dtype=float32)
 y: array([[[ 0.999996,  0.999996],
        [ 0.999999,  0.999996],
        [ 1.      ,  1.      ]]], dtype=float32)

----------------------------------------------------------------------
Ran 2 tests in 7.192s

FAILED (failures=1)
not close where =  (array([0, 0, 0], dtype=int32), array([0, 0, 1], dtype=int32), array([0, 1, 1], dtype=int32))
not close lhs =  [ 1.  1.  1.]
not close rhs =  [ 0.99999619  0.99999619  0.99999619]
not close dif =  [  3.81469727e-06   3.81469727e-06   3.81469727e-06]
not close tol =  [  1.99999613e-06   1.99999613e-06   1.99999613e-06]
