exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
.F.
======================================================================
FAIL: testBCast_5D (__main__.BinaryOpTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pi/.cache/bazel/_bazel_pi/4770c5ca1786316d370c900c0b614a6d/tensorflow/bazel-out/local_linux-py3-opt/bin/tensorflow/python/kernel_tests/cwise_ops_test.runfiles/tensorflow/python/kernel_tests/cwise_ops_test.py", line 863, in testBCast_5D
    self._testBCastD([1, 3, 2], [2, 3, 1])
  File "/home/pi/.cache/bazel/_bazel_pi/4770c5ca1786316d370c900c0b614a6d/tensorflow/bazel-out/local_linux-py3-opt/bin/tensorflow/python/kernel_tests/cwise_ops_test.runfiles/tensorflow/python/kernel_tests/cwise_ops_test.py", line 791, in _testBCastD
    self._testBCastByFunc(funcs, xs, ys)
  File "/home/pi/.cache/bazel/_bazel_pi/4770c5ca1786316d370c900c0b614a6d/tensorflow/bazel-out/local_linux-py3-opt/bin/tensorflow/python/kernel_tests/cwise_ops_test.runfiles/tensorflow/python/kernel_tests/cwise_ops_test.py", line 759, in _testBCastByFunc
    self._compareBCast(xs, ys, dtype, np_func, tf_func)
  File "/home/pi/.cache/bazel/_bazel_pi/4770c5ca1786316d370c900c0b614a6d/tensorflow/bazel-out/local_linux-py3-opt/bin/tensorflow/python/kernel_tests/cwise_ops_test.runfiles/tensorflow/python/kernel_tests/cwise_ops_test.py", line 727, in _compareBCast
    self._compareCpu(x, y, np_func, tf_func)
  File "/home/pi/.cache/bazel/_bazel_pi/4770c5ca1786316d370c900c0b614a6d/tensorflow/bazel-out/local_linux-py3-opt/bin/tensorflow/python/kernel_tests/cwise_ops_test.runfiles/tensorflow/python/kernel_tests/cwise_ops_test.py", line 448, in _compareCpu
    self.assertAllClose(np_ans, tf_cpu)
  File "/home/pi/.cache/bazel/_bazel_pi/4770c5ca1786316d370c900c0b614a6d/tensorflow/bazel-out/local_linux-py3-opt/bin/tensorflow/python/kernel_tests/cwise_ops_test.runfiles/tensorflow/python/framework/test_util.py", line 442, in assertAllClose
    np.testing.assert_allclose(a, b, rtol=rtol, atol=atol)
  File "/usr/local/lib/python3.4/dist-packages/numpy/testing/utils.py", line 1391, in assert_allclose
    verbose=verbose, header=header)
  File "/usr/local/lib/python3.4/dist-packages/numpy/testing/utils.py", line 733, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-06, atol=1e-06

(mismatch 41.666666666666664%)
 x: array([[[ 1.      ,  2.      ],
        [ 1.5     ,  2.      ],
        [ 1.666667,  2.      ]],...
 y: array([[[ 0.999996,  1.999992],
        [ 1.499994,  1.999992],
        [ 1.666665,  1.999998]],...

----------------------------------------------------------------------
Ran 3 tests in 32.869s

FAILED (failures=1)
not close where =  (array([0, 0, 0, 0, 1], dtype=int32), array([0, 0, 1, 1, 0], dtype=int32), array([0, 1, 0, 1, 1], dtype=int32))
not close lhs =  [ 1.   2.   1.5  2.   0.5]
not close rhs =  [ 0.99999619  1.99999237  1.49999428  1.99999237  0.49999809]
not close dif =  [  3.81469727e-06   7.62939453e-06   5.72204590e-06   7.62939453e-06
   1.90734863e-06]
not close tol =  [  1.99999613e-06   2.99999238e-06   2.49999425e-06   2.99999238e-06
   1.49999801e-06]
